### ISSUE TITLE
add .h

### ISSUE THREAD

**Issue by ramarro123** [judge2005/ESPAsyncHttpClient#1]
@judge2005, i know that the lib it's not released nor supported, but do you mind to add the .h file? just to make it compiling, at the moment it doesn't build due to lack of imports

**Comment by judge2005** [comment]
Hi

I will take a look at it, but that would require some refactoring. All I do is to copy and paste the entire class in to my sketch, rather than include it as a library. I just put it in a .cpp file because it had to be insonething!

**Comment by judge2005** [comment]
Better late than never...
